spring:
  datasource:
    hikari:
      maxLifetime: '200000'
      connectionTimeout: '30000'
      minimumIdle: '5'
      poolName: SpringBootJPAHikariCP
      idleTimeout: '30000'
      connection-test-query: SELECT 1
      maximumPoolSize: '20'
    initialization-mode: always
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2dll:
          create_namespaces: 'true'
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        default_schema: beehyv
      javax:
        persistence:
          create-database-schemas: 'true'
          schema-generation:
            database:
              action: create
    show-sql: 'true'
    open-in-view: 'false'
springdoc:
  api-docs:
    resolve-schema-properties: 'true'
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: 'true'
  version: '@springdoc.version@'
server:
  port: 8080
logging:
  level:
    root: INFO
management:
  endpoint:
    beans:
      enabled: 'false'
endpoints:
  web:
    exposure:
      include: '*'
jwt:
  token:
    prefix: Bearer
    validityInSec: 1800
  refreshToken:
    validityInSec: 18000
  header:
    string: Authorization
  signing:
    key: ${JWT_SIGNING_KEY}
  authorities:
    key: roles
